# Generated by Django 2.2.3 on 2019-07-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expens',
            new_name='Expense',
        ),
    ]
