# Generated by Django 2.2.3 on 2019-07-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190724_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
